(dp1
S'output'
p2
S"<type 'exceptions.IOError'> File C:\\Work\\web2py\\applications\\bootcamp_Jeremy\\\\data\\dataset_1\\Video_Games_Sales_as_at_22_Dec_2016.csv does not exist"
p3
sS'layer'
p4
S'C:\\Work\\web2py\\applications\\bootcamp_Jeremy\\controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 000000000F2A0030, file "C:\\Work\\web2py\\applications\\bootcamp_Jeremy\\controllers/default.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Work\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Work\\web2py\\applications\\bootcamp_Jeremy\\controllers/default.py", line 81, in <module>\n  File "C:\\Work\\web2py\\gluon\\globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "C:\\Work\\web2py\\applications\\bootcamp_Jeremy\\controllers/default.py", line 18, in get_data\n    df = pandas.read_csv(path + \'private\\\\data\\\\dataset_1\\\\Video_Games_Sales_as_at_22_Dec_2016.csv\')\n  File "C:\\Anaconda\\lib\\site-packages\\pandas\\io\\parsers.py", line 655, in parser_f\n    return _read(filepath_or_buffer, kwds)\n  File "C:\\Anaconda\\lib\\site-packages\\pandas\\io\\parsers.py", line 405, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File "C:\\Anaconda\\lib\\site-packages\\pandas\\io\\parsers.py", line 762, in __init__\n    self._make_engine(self.engine)\n  File "C:\\Anaconda\\lib\\site-packages\\pandas\\io\\parsers.py", line 966, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n  File "C:\\Anaconda\\lib\\site-packages\\pandas\\io\\parsers.py", line 1582, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File "pandas\\_libs\\parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas\\_libs\\parsers.c:4209)\n  File "pandas\\_libs\\parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas\\_libs\\parsers.c:8873)\nIOError: File C:\\Work\\web2py\\applications\\bootcamp_Jeremy\\\\data\\dataset_1\\Video_Games_Sales_as_at_22_Dec_2016.csv does not exist\n'
p11
s.